# Generated by Django 6.0.3 on 2026-03-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empolyee',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('HR', 'HR'), ('Finance', 'Finance'), ('Sales', 'Sales')], max_length=30),
        ),
        migrations.AlterField(
            model_name='empolyee',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
